### ISSUE TITLE
[REQ] Also getting confirmations in Persian

### ISSUE THREAD

**Issue by iMat1n** [MahdyMirzade/dumBash#2]
### Plugin turns second layout ( FA ) to English, but confirmations are received in English ( y/n ). So why not also receiving them through Persian ?

**eg.**
```
>> افخح
Did you mean htop ? (y/n) غ
Running: htop...
```

**Comment by MahdiMirzadeh** [comment]
Done [@46ddb76](https://github.com/MahdyMirzade/dumBash/commit/46ddb7666b68acda6723a7d45e0b4508cd9920ea)

New Confirmation Options Alternatives in Persian:
- Y = د/ص/ب
- N = ن/غ/خ
- Yes = درست/صحیح/بله 
- No = نادرست/غلط/خیر
